version: '3.9'

services:
  db:
    image: postgis/postgis:15-3.3
    environment:
      POSTGRES_USER: motor_reserva
      POSTGRES_PASSWORD: motor_reserva
      POSTGRES_DB: motor_reservas
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      DJANGO_ENV: production
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - db

  celery_worker:
    build: .
    command: celery -A core worker --loglevel=info --concurrency=4
    env_file:
      - .env
    environment:
      DJANGO_ENV: production
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - redis
      - web

  celery_beat:
    build: .
    command: celery -A core beat --loglevel=info
    env_file:
      - .env
    environment:
      DJANGO_ENV: production
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - redis
      - web

volumes:
  static_volume:
  media_volume:
  pgdata:
