services:
  db:
    image: postgis/postgis:15-3.3
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  web:
    build: .
    command: ["/app/bin/entrypoint.sh"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=1
      - DB_NAME=mydb
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_HOST=db
      - GDAL_LIBRARY_PATH=/usr/lib/libgdal.so
      - AWS_S3_REGION_NAME=asd
      - AWS_ACCESS_KEY_ID=asd
      - AWS_SECRET_ACCESS_KEY=asd
      - AWS_STORAGE_BUCKET_NAME=asd
      - MY_FRONTEND_SECRET_TOKEN=asd

volumes:
  postgres_data:
