# Generated by Django 5.2.1 on 2025-06-16 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0001_initial'),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pms',
            name='pms_external_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='PMSDataResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function_name', models.CharField(max_length=255)),
                ('response_data', models.JSONField(verbose_name='Response Data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField(blank=True, default=None, null=True)),
                ('end_date', models.DateField(blank=True, default=None, null=True)),
                ('pms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pms_data_responses', to='pms.pms')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pms_data_responses', to='properties.property')),
            ],
            options={
                'verbose_name': 'PMS Data Response',
                'verbose_name_plural': 'PMS Data Responses',
                'db_table': 'pms_data_response',
                'ordering': ['-created_at'],
            },
        ),
    ]
