# Generated by Django 5.2.1 on 2025-06-09 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0003_pmsdataresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='pmsdataresponse',
            name='end_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='pmsdataresponse',
            name='start_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
