# Generated by Django 5.2.1 on 2025-06-04 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_alter_reservation_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='guest_cp',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Código postal del huésped'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='guest_remarks',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones del huésped'),
        ),
        migrations.AlterField(
            model_name='reservationroom',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='reservations.reservation'),
        ),
    ]
