# Generated by Django 5.2.1 on 2025-07-09 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_remove_room_services_service_property'),
        ('reservations', '0003_reservation_payment_amount_reservation_payment_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentNotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('raw_parameters', models.TextField()),
                ('signature', models.CharField(max_length=512)),
                ('order_id', models.CharField(db_index=True, max_length=64)),
                ('is_valid', models.BooleanField(default=False)),
                ('message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'payment_notification_logs',
                'ordering': ['-received_at'],
            },
        ),
        migrations.AddField(
            model_name='reservationroom',
            name='room_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.roomtype'),
        ),
    ]
