# Generated by Django 5.2.1 on 2025-06-05 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_reservation_guest_cp_reservation_guest_remarks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('ok', 'Ok')], default='pending', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterModelTable(
            name='reservationroom',
            table='reservation_rooms',
        ),
    ]
