# Generated by Django 5.2.1 on 2025-07-10 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_remove_room_services_service_property'),
        ('reservations', '0004_paymentnotificationlog_reservationroom_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationroom',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.room'),
        ),
    ]
