# Generated by Django 5.2.1 on 2025-07-15 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_alter_roomtype_name_alter_roomtype_unique_together'),
        ('reservations', '0005_alter_reservationroom_room'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservationroom',
            unique_together={('reservation', 'room_type')},
        ),
    ]
