# Generated by Django 5.2.1 on 2025-08-06 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0010_reservation_discount_fields'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservationroom',
            unique_together=set(),
        ),
    ]
