# Generated by Django 5.2.1 on 2025-05-20 19:10

import properties.models
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomimage',
            name='image',
            field=models.ImageField(storage=storages.backends.s3.S3Storage(), upload_to=properties.models.room_image_upload_path),
        ),
    ]
