# Generated by Django 5.2.1 on 2025-06-16 18:19

import django.db.models.deletion
import properties.models
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0002_pms_pms_external_id_pmsdataresponse'),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('external_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID Externo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tipo de Habitación',
                'verbose_name_plural': 'Tipos de Habitaciones',
                'db_table': 'room_types',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='property',
            name='pms',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='pms.pms', verbose_name='PMS'),
        ),
        migrations.AddField(
            model_name='property',
            name='use_pms_information',
            field=models.BooleanField(default=False, help_text='Si está marcado, se utilizará la información del PMS para esta propiedad.', verbose_name='Usar información del PMS'),
        ),
        migrations.AddField(
            model_name='room',
            name='external_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='external_room_type_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='external_room_type_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='roomimage',
            name='image',
            field=models.ImageField(storage=storages.backends.s3.S3Storage(), upload_to=properties.models.room_image_upload_path),
        ),
        migrations.CreateModel(
            name='PmsDataProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_url', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Base URL')),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True, verbose_name='Email')),
                ('phone_number', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Teléfono')),
                ('pms_token', models.CharField(blank=True, default=None, null=True)),
                ('pms_hotel_identifier', models.CharField(blank=True, default=None, null=True)),
                ('pms_username', models.CharField(blank=True, default=None, null=True)),
                ('pms_password', models.CharField(blank=True, default=None, null=True)),
                ('pms_property_id', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('pms_property_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('pms_property_address', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('pms_property_city', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('pms_property_province', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('pms_property_postal_code', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('pms_property_country', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('pms_property_latitude', models.FloatField(blank=True, default=None, null=True, verbose_name='Latitud')),
                ('pms_property_longitude', models.FloatField(blank=True, default=None, null=True, verbose_name='Longitud')),
                ('pms_property_phone', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Teléfono PMS')),
                ('pms_property_category', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Categoría PMS')),
                ('first_sync', models.BooleanField(default=True, verbose_name='Primera sincronización')),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pms_data', to='properties.property')),
            ],
            options={
                'verbose_name': 'Datos PMS',
                'verbose_name_plural': 'Datos PMS',
                'db_table': 'pms_data_property',
            },
        ),
        migrations.AlterField(
            model_name='room',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='properties.roomtype', verbose_name='Tipo de Habitación'),
        ),
        migrations.CreateModel(
            name='TermsAndConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_of_confirmation', models.TextField(blank=True, null=True, verbose_name='Condición de Confirmación')),
                ('check_in_time', models.CharField(blank=True, max_length=50, null=True, verbose_name='Hora de Check-in')),
                ('check_out_time', models.CharField(blank=True, max_length=50, null=True, verbose_name='Hora de Check-out')),
                ('cancellation_policy', models.TextField(blank=True, null=True, verbose_name='Política de Cancelación')),
                ('additional_information', models.TextField(blank=True, null=True, verbose_name='Información Adicional')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='terms_and_conditions', to='properties.property')),
            ],
            options={
                'verbose_name': 'Términos y Condiciones',
                'verbose_name_plural': 'Términos y Condiciones',
                'db_table': 'terms_and_conditions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('availability', models.IntegerField()),
                ('rates', models.JSONField(blank=True, default=None, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='properties.property')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='properties.roomtype', verbose_name='Tipo de Habitación')),
            ],
            options={
                'verbose_name': 'Disponibilidad',
                'verbose_name_plural': 'Disponibilidades',
                'db_table': 'availability',
                'ordering': ['-date'],
                'unique_together': {('property', 'room_type', 'date')},
            },
        ),
    ]
