# Generated by Django 5.2.1 on 2025-05-23 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0001_initial'),
        ('properties', '0002_alter_roomimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='base_url',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Base URL'),
        ),
        migrations.AddField(
            model_name='property',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='property',
            name='phone_number',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Teléfono'),
        ),
        migrations.AddField(
            model_name='property',
            name='pms',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='pms.pms', verbose_name='PMS'),
        ),
        migrations.AddField(
            model_name='property',
            name='pms_hotel_identifier',
            field=models.CharField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='pms_password',
            field=models.CharField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='pms_token',
            field=models.CharField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='pms_username',
            field=models.CharField(blank=True, default=None, null=True),
        ),
    ]
