# Generated by Django 5.2.1 on 2025-05-29 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_base_url_property_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsAndConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_of_confirmation', models.TextField(blank=True, null=True, verbose_name='Condición de Confirmación')),
                ('check_in_time', models.CharField(blank=True, max_length=50, null=True, verbose_name='Hora de Check-in')),
                ('check_out_time', models.CharField(blank=True, max_length=50, null=True, verbose_name='Hora de Check-out')),
                ('cancellation_policy', models.TextField(blank=True, null=True, verbose_name='Política de Cancelación')),
                ('additional_information', models.TextField(blank=True, null=True, verbose_name='Información Adicional')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms_and_conditions', to='properties.property')),
            ],
            options={
                'verbose_name': 'Términos y Condiciones',
                'verbose_name_plural': 'Términos y Condiciones',
                'db_table': 'terms_and_conditions',
                'ordering': ['-created_at'],
            },
        ),
    ]
