# Generated by Django 5.2.1 on 2025-06-24 18:44

import django.db.models.deletion
import properties.models
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_alter_property_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to=properties.models.property_image_upload_path, verbose_name='Imagen de Portada'),
        ),
        migrations.CreateModel(
            name='RoomTypeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(storage=storages.backends.s3.S3Storage(), upload_to=properties.models.property_image_upload_path, verbose_name='Imagen')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.roomtype', verbose_name='Tipo de Habitación')),
            ],
            options={
                'verbose_name': 'Imagen de Tipo de Habitación',
                'verbose_name_plural': 'Imágenes de Tipos de Habitaciones',
                'db_table': 'room_type_images',
                'ordering': ['-id'],
            },
        ),
    ]
