# Generated by Django 5.2.1 on 2025-06-02 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0001_initial'),
        ('properties', '0005_alter_termsandconditions_property'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='base_url',
        ),
        migrations.RemoveField(
            model_name='property',
            name='email',
        ),
        migrations.RemoveField(
            model_name='property',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='property',
            name='pms',
        ),
        migrations.RemoveField(
            model_name='property',
            name='pms_hotel_identifier',
        ),
        migrations.RemoveField(
            model_name='property',
            name='pms_password',
        ),
        migrations.RemoveField(
            model_name='property',
            name='pms_token',
        ),
        migrations.RemoveField(
            model_name='property',
            name='pms_username',
        ),
        migrations.CreateModel(
            name='PmsDataProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_url', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Base URL')),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True, verbose_name='Email')),
                ('phone_number', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Teléfono')),
                ('pms_token', models.CharField(blank=True, default=None, null=True)),
                ('pms_hotel_identifier', models.CharField(blank=True, default=None, null=True)),
                ('pms_username', models.CharField(blank=True, default=None, null=True)),
                ('pms_password', models.CharField(blank=True, default=None, null=True)),
                ('pms', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='pms.pms', verbose_name='PMS')),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pms_data', to='properties.property')),
            ],
            options={
                'verbose_name': 'Datos PMS de Propiedad',
                'verbose_name_plural': 'Datos PMS de Propiedades',
                'db_table': 'pms_data_property',
            },
        ),
    ]
