# Generated by Django 5.2.1 on 2025-06-24 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_roomtype_cover_image_roomtypeimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='services',
        ),
        migrations.AddField(
            model_name='service',
            name='property',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='properties.property', verbose_name='Propiedad'),
            preserve_default=False,
        ),
    ]
