# Generated by Django 5.2.1 on 2025-07-11 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_remove_room_services_service_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_types', to='properties.property', verbose_name='Propiedad'),
        ),
    ]
