# Generated by Django 5.2.1 on 2025-06-03 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_remove_pmsdataproperty_pms_property_pms'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pmsdataproperty',
            options={'verbose_name': 'Datos PMS', 'verbose_name_plural': 'Datos PMS'},
        ),
    ]
