# Generated by Django 5.2.1 on 2025-07-11 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_roomtype_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterUniqueTogether(
            name='roomtype',
            unique_together={('name', 'property')},
        ),
    ]
