# Generated by Django 5.2.1 on 2025-06-03 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_alter_pmsdataproperty_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='type',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('studio', 'Studio'), ('duplex', 'Duplex'), ('room', 'Room'), ('suite', 'Suite'), ('loft', 'Loft'), ('cabin', 'Cabin'), ('penthouse', 'Penthouse')], max_length=20, verbose_name='Tipo'),
        ),
    ]
