# Generated by Django 5.2.1 on 2025-06-03 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_alter_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='external_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
