# Generated by Django 5.2.1 on 2025-08-30 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0010_alter_room_description"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="service",
            unique_together={("property", "name")},
        ),
    ]
