# Generated by Django 5.2.1 on 2025-06-04 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_room_external_room_type_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pmsdataproperty',
            name='pms_property_address',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pmsdataproperty',
            name='pms_property_category',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Categoría PMS'),
        ),
        migrations.AddField(
            model_name='pmsdataproperty',
            name='pms_property_city',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pmsdataproperty',
            name='pms_property_country',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pmsdataproperty',
            name='pms_property_id',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='pmsdataproperty',
            name='pms_property_latitude',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Latitud'),
        ),
        migrations.AddField(
            model_name='pmsdataproperty',
            name='pms_property_longitude',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Longitud'),
        ),
        migrations.AddField(
            model_name='pmsdataproperty',
            name='pms_property_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pmsdataproperty',
            name='pms_property_phone',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Teléfono PMS'),
        ),
        migrations.AddField(
            model_name='pmsdataproperty',
            name='pms_property_postal_code',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pmsdataproperty',
            name='pms_property_province',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
