# Generated by Django 5.2.1 on 2025-08-06 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_service_code_and_property_service'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='availability',
            unique_together=set(),
        ),
    ]
