# Generated by Django 5.2.1 on 2025-06-05 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_pmsdataproperty_pms_property_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='use_pms_information',
            field=models.BooleanField(default=False, help_text='Si está marcado, se utilizará la información del PMS para esta propiedad.', verbose_name='Usar información del PMS'),
        ),
    ]
