# Generated by Django 5.2.1 on 2025-06-05 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0013_property_use_pms_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='pmsdataproperty',
            name='first_sync',
            field=models.BooleanField(default=True, verbose_name='Primera sincronización'),
        ),
    ]
