# Generated by Django 5.2.1 on 2025-08-06 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0013_alter_availability_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='availability',
            unique_together={('property', 'room_type', 'date')},
        ),
    ]
