# Generated by Django 5.2.1 on 2025-08-06 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0014_alter_availability_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoomService",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "room_type",
                    models.ForeignKey(
                        on_delete=models.CASCADE,
                        related_name="room_services",
                        to="properties.roomtype",
                        verbose_name="Tipo de Habitación",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=models.CASCADE,
                        related_name="room_services",
                        to="properties.service",
                        verbose_name="Servicio",
                    ),
                ),
                (
                    "property_service",
                    models.ForeignKey(
                        on_delete=models.CASCADE,
                        related_name="room_services",
                        to="properties.propertyservice",
                        verbose_name="Servicio de Propiedad",
                    ),
                ),
            ],
            options={
                "db_table": "room_services",
                "verbose_name": "Servicio de Habitación",
                "verbose_name_plural": "Servicios de Habitaciones",
                "unique_together": {("room_type", "service")},
            },
        ),
        migrations.AddField(
            model_name="roomtype",
            name="services",
            field=models.ManyToManyField(
                blank=True,
                related_name="room_types",
                through="properties.RoomService",
                to="properties.service",
                verbose_name="Servicios",
            ),
        ),
    ]
