# Generated by Django 5.2.1 on 2025-06-06 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0014_pmsdataproperty_first_sync'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('external_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID Externo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tipo de Habitación',
                'verbose_name_plural': 'Tipos de Habitaciones',
                'db_table': 'room_types',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='room',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='properties.roomtype', verbose_name='Tipo de Habitación'),
        ),
    ]
