# Generated by Django 5.2.1 on 2025-08-05 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0004_add_coupon_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcoupon',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
    ]
