# Generated by Django 5.2.1 on 2025-05-15 23:07

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import storages.backends.s3
import zones.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('area', django.contrib.gis.db.models.fields.PolygonField(blank=True, geography=True, null=True, srid=4326)),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('cover_image', models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to=zones.models.zone_cover_image_upload_path, verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'Zona',
                'verbose_name_plural': 'Zonas',
                'db_table': 'zones',
            },
        ),
        migrations.CreateModel(
            name='ZoneImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(storage=storages.backends.s3.S3Storage(), upload_to=zones.models.zone_image_upload_path, verbose_name='Imagen')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Descripción')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='zones.zone', verbose_name='Zona')),
            ],
            options={
                'verbose_name': 'Imagen de Zona',
                'verbose_name_plural': 'Imágenes de Zonas',
                'ordering': ['-id'],
            },
        ),
    ]
