# Generated by Django 5.2.1 on 2025-06-16 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zoneimage',
            options={'verbose_name': 'Imagen de Zona', 'verbose_name_plural': 'Imágenes de Zonas'},
        ),
        migrations.AlterField(
            model_name='zoneimage',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_images', to='zones.zone', verbose_name='Zona'),
        ),
        migrations.AlterModelTable(
            name='zoneimage',
            table='zone_images',
        ),
    ]
