# Generated by Django 5.2.1 on 2025-05-20 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zoneimage',
            options={'verbose_name': 'Imagen de Zona', 'verbose_name_plural': 'Imágenes de Zonas'},
        ),
        migrations.AlterModelTable(
            name='zoneimage',
            table='zone_images',
        ),
    ]
