# Generated by Django 5.2.1 on 2025-05-20 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zones', '0002_alter_zoneimage_options_alter_zoneimage_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zoneimage',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_images', to='zones.zone', verbose_name='Zona'),
        ),
    ]
