name: Build And Push Docker
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Generar número de versión basado en el contador de commits
      - name: Generate Version
        id: version
        run: |
          commit_count=$(git rev-list --count HEAD)
          echo "VERSION=1.0.${commit_count}" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Login to my Registry
        uses: docker/login-action@v3
        with:
          registry: https://docker.divergtech.com
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build And Push Backend
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          platforms: linux/amd64
          provenance: false
          tags: |
            docker.divergtech.com/back-hba:v${{ steps.version.outputs.VERSION }}
            docker.divergtech.com/back-hba:latest
